objects/Project__c.object
<CustomObject>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Sprint__c.object
<CustomObject>
    <fields>
        <fullName>Project__c</fullName>
        <label>Project</label>
        <referenceTo>Project__c</referenceTo>
        <relationshipLabel>ProjectToSprint</relationshipLabel>
        <relationshipName>ProjectToSprint</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Sprint</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Sprints</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/WorkItem__c.object
<CustomObject>
    <fields>
        <fullName>Sprint__c</fullName>
        <label>Sprint</label>
        <referenceTo>Sprint__c</referenceTo>
        <relationshipLabel>SprintToWorkItems</relationshipLabel>
        <relationshipName>SprinToWorkItems</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Not Started</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>In Progress</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Done</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Story_Points__c</fullName>
        <description>Work item story points. It can only be 1, 2, 3, 5, 8 or 13.</description>
        <label>Story Points</label>
        <picklist>
            <picklistValues>
                <fullName>1</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>8</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>13</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>WorkItem</label>
    <nameField>
        <label>WorkItem Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>WorkItems</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/WorkItemRelatedStoryPoints.cls
public with sharing class WorkItemRelatedStoryPoints
{
    private final WorkItem__c workItem;
    
    public List<WorkItem__c> workItems {get; set;}
    
	public List<SelectOption> statusList {get; set;}
    
    public String statusOption {get; set;}
    
    public Sprint__c sprint;
    
    public WorkItemRelatedStoryPoints(ApexPages.StandardController stdController)
    {
        System.debug('Constructor    ' );
        this.workItem = [SELECT Id, Name, Sprint__c, Story_Points__c, Status__c FROM WorkItem__c WHERE Id =: ((WorkItem__c)stdController.getRecord()).Id];
        sprint = [SELECT Id, Project__c FROM Sprint__c WHERE Id=: this.workItem.Sprint__c];
        this.statusList = getStatusList();
        workItems = getItems();
    }
    
	private List<WorkItem__c> getItems()
    {   
        workItems = new List<WorkItem__c>();
        System.debug('Status Option    ' + statusOption);
        if(statusOption == 'All Status' || statusOption == null)
        {
            workItems = [SELECT Id, Name, Sprint__r.Project__c, Story_Points__c, Status__c
                                       FROM WorkItem__c WHERE Story_Points__c =: this.workItem.Story_Points__c AND 
                                       Sprint__r.Project__c =: sprint.Project__c];
        } else
        {
            workItems = [SELECT Id, Name, Sprint__r.Project__c, Story_Points__c, Status__c
                                       FROM WorkItem__c WHERE Story_Points__c =: this.workItem.Story_Points__c AND 
                                       Sprint__r.Project__c =: sprint.Project__c AND Status__c=: statusOption];
        }
        return workItems;
    }
    
    public List<SelectOption> getStatusList() {
        List<SelectOption> statusList = new List<SelectOption>();
        statusList.add(new SelectOption('All Status','All Status'));
		statusList.add(new SelectOption('Not Started','Not Started'));
        statusList.add(new SelectOption('In Progress','In Progress'));
        statusList.add(new SelectOption('Done','Done'));
        return statusList;
    }

    public PageReference test()
    {
        workItems = getItems();
		System.debug('entro ');
        return null;
    }
}